#!/usr/bin/env python

import sys
import string

with open('hat_zero_brick.eep', 'rb') as f:
    zero = f.read()

content = """// generated by ../../rpi/create_eeprom_data_c.py
#include <eeprom_data.h>

const uint8_t eeprom_data[] = {{{data}}};
""".format(data=",".join([str(x) for x in zero]))

header = """// generated by ../../rpi/create_eeprom_data_c.py
#include <stdint.h>

extern const uint8_t eeprom_data[];
"""

with open("../software/src/eeprom_data.c", "w") as f:
    f.write(content)

with open("../software/src/eeprom_data.h", "w") as f:
    f.write(header)
